// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    CarbonArrowRight: typeof import('~icons/carbon/arrow-right')['default']
    CarbonChevronUp: typeof import('~icons/carbon/chevron-up')['default']
    CarbonDeliveryParcel: typeof import('~icons/carbon/delivery-parcel')['default']
    CarbonShare: typeof import('~icons/carbon/share')['default']
    CarbonThumbsUp: typeof import('~icons/carbon/thumbs-up')['default']
    Card: typeof import('./components/Card.vue')['default']
    CardImage: typeof import('./components/CardImage.vue')['default']
    CardSelect: typeof import('./components/CardSelect.vue')['default']
    Notifications: typeof import('./components/notifications.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
